### ISSUE TITLE
Don't hard code Templates location

### ISSUE THREAD

**Issue by stonematt** [quanru/obsidian-lifeos#51]
In general, I put my templates in a folder called zz_templates, so it sorts to the bottom. When I renamed your Templates folder to this, I got and error (see image below).  Please update to support alternative template locations.

![CleanShot 2024-03-05 at 20 21 46@2x](https://github.com/quanru/obsidian-periodic-para/assets/2821486/fe618712-e3ec-4b38-bac7-9b21105456fb)

**Comment by eportzxp** [comment]
The same type issue, include daily log folder, weekly log folder, and so on, please don't hard code them.

**Comment by wedgen** [comment]
I get this even using the example vault.

**Comment by quanru** [comment]
Now support through advanced settings:
![image](https://github.com/quanru/obsidian-lifeos/assets/11739753/3a10f613-b3db-44f3-bfbb-7fdf08c36987)
![image](https://github.com/quanru/obsidian-lifeos/assets/11739753/26c44d64-a31b-4df7-8c34-878d1576dadf)
