### ISSUE TITLE
Add indicators to dates which have notes recorded

### ISSUE THREAD

**Issue by FilipLaz** [quanru/obsidian-lifeos#52]
Hi,

It would be useful to add indicators to dates that have notes recorded, example how it could look like:
![example](https://github.com/quanru/obsidian-periodic-para/assets/4378518/2656cf28-cff6-4e7e-aee6-1e03ba18b9a5)

**Comment by quanru** [comment]
1.13.0 support it: https://obsidian-life-os.netlify.app/news/apr-changelog.html
