### ISSUE TITLE
Preference for Index filename

### ISSUE THREAD

**Issue by rjmoggach** [quanru/obsidian-lifeos#58]
Feature Request:

Would prefer if the default index file was the folder name and/or customizable. 

This works really well with the [Folder Notes](https://github.com/LostPaul/obsidian-folder-notes) plugin.

Instead of:

      itemIndex ? itemIndex + ".README.md" : ""

just this:

      itemIndex ? itemIndex + ".md" : ""

**Comment by rjmoggach** [comment]
![image](https://github.com/quanru/obsidian-periodic-para/assets/184759/17679feb-1459-4bcc-99b0-35954849d3d9)

**Comment by quanru** [comment]
Currently, same-named index files are supported. Please refer to the reason why they are not set as default: https://github.com/quanru/obsidian-periodic-para/issues/49#issuecomment-1973356728

I do want to open up some configurations and put them separately in advanced settings, but currently I don't have time to do so.

**Comment by rjmoggach** [comment]
sounds good - a preference for the defaults would be nice at some point so count it as a feature request, not a bug

**Comment by quanru** [comment]
1.13.0 support it: https://obsidian-life-os.netlify.app/news/apr-changelog.html
