### ISSUE TITLE
Changing the week to start from Saturday to friday

### ISSUE THREAD

**Issue by AbuEssam-Ahmed-helmy** [quanru/obsidian-lifeos#61]
is it possible to change the week' included days to be Sat to Friday of the corresponding week instead of Sun to Sat?

**Comment by quanru** [comment]
Do you mean changing the start time of the week? It could be Monday or Sunday

**Comment by AbuEssam-Ahmed-helmy** [comment]
Yes, I mean this, but is there a way to make it start on Saturday? this is the start of my week and other millions of Muslims living in Muslim countries.

**Comment by quanru** [comment]
I will open the setting of the starting date of the week in the future. I'll remember it first. I don't think it will be that fast.

**Comment by quanru** [comment]
1.13.0 support it: https://obsidian-life-os.netlify.app/news/apr-changelog.html
