### ISSUE TITLE
Custom Weekly Template

### ISSUE THREAD

**Issue by chengyu0910** [quanru/obsidian-lifeos#62]
The current weekly not title has the form like Year-#Weak. How to modify the weekly template so that the title of the weekly note contains the date duration like 2024-W22(04/23-04/30)?

**Comment by quanru** [comment]
It is not supported yet.

**Comment by quanru** [comment]
ref: https://github.com/liamcain/obsidian-calendar-plugin/blob/master/src/io/weeklyNotes.ts#L22

**Comment by quanru** [comment]
![image](https://github.com/quanru/obsidian-lifeos/assets/11739753/5cf8b0fa-d97a-4303-8c16-849d58348dae)

**Comment by quanru** [comment]
cc @zytomorrow Interested?

**Comment by zytomorrow** [comment]
可以考虑适配下

**Comment by quanru** [comment]
Duplicate #85
