### ISSUE TITLE
存量memos同步, 日记不存在会有一堆报警,  可能考虑屏蔽下

### ISSUE THREAD

**Issue by alonWang** [quanru/obsidian-lifeos#63]
https://github.com/quanru/obsidian-lifeos/blob/5653036fdb32dfa700aafe29a45ef400bb5cc5b0/src/periodic/DailyRecord.ts#L216

**Comment by quanru** [comment]
如果不报警，用户就不知道没被同步，就会丢失数据了

**Comment by alonWang** [comment]
背景: 最近才开始使用lifeos, 但是很早就开始使用memos了
对于旧的memos   不同步也没关系,   但是每次启动都弹一堆tip就很难受了
![image](https://github.com/quanru/obsidian-lifeos/assets/11813982/8455fb71-5f22-49a8-8461-3f9d8512a8df)

**Comment by quanru** [comment]
我加个开关吧

**Comment by alonWang** [comment]
感谢!

**Comment by quanru** [comment]
![image](https://github.com/quanru/obsidian-lifeos/assets/11739753/02045e67-7de2-432b-b45b-4eeda7f98e02)
version 1.13.1

**Comment by quanru** [comment]
![image](https://github.com/quanru/obsidian-lifeos/assets/11739753/eb4c9066-5cc1-44ca-9067-89bea469a378)
version 1.13.1
