### ISSUE TITLE
Memos 拉取失败

### ISSUE THREAD

**Issue by jackiontop11** [quanru/obsidian-lifeos#64]
我想请教一下，我的 Memos 拉取突然出现故障。Obsidian 报错显示：

“拉取 usememos 失败: AxiosError: Network Error”

Memos 是部署在 Koyeb 上的，检查后该服务器状态没有问题。重新更新了 api 和 token 均无法修复。

无魔法不报错，但无法同步; 有则报错。

<img width="301" alt="iShot_2024-05-18_07 08 23" src="https://github.com/quanru/obsidian-lifeos/assets/114744626/ea342f3d-ead6-4ad1-8524-5c993eea021d">

**Comment by zhuhaoxlj** [comment]
我的也遇到了类似的问题：
`拉取 usememos 失败: Error: "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon.png\" />\n    <link rel=\"icon\" type=\"image/webp\" href=\"/logo.webp\" />\n    <link rel=\"manifest\" href=\"/site.webmanifest\" />\n    <meta name=\"theme-color\" media=\"(prefers-color-scheme: light)\" content=\"#f4f4f5\" />\n    <meta name=\"theme-color\" media=\"(prefers-color-scheme: dark)\" content=\"#18181b\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n    <!-- memos.metadata.head -->\n    <title>Memos</title>\n    <script>\n      // Prevent flash of light mode.\n      const appearance = localStorage.getItem(\"appearance\");\n      if (appearance === `\"dark\"`) {\n        document.documentElement.classList.add(\"dark\");\n      }\n    </script>\n    <script type=\"module\" crossorigin src=\"/assets/index-BlexmZ_L.js\"></script>\n    <link rel=\"stylesheet\" crossorigin href=\"/assets/index-CcXvRfz2.css\">\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <!-- memos.metadata.body -->\n  </body>\n</html>\n"`
报错位置：
`function logMessage(message, level = 0 /* info */) {
  new import_obsidian4.Notice(message, 5e3);
  if (level === 0 /* info */) {
    console.info(message);
  } else if (level === 1 /* warn */) {
    console.warn(message);
  } else if (level === 2 /* error */) {
    console.error(message);
    throw Error(message);
  }
}`

**Comment by quanru** [comment]
0.22.0 的 memos 下了 v1 的接口

**Comment by lufan-cn** [comment]
> 0.22.0 的 memos 删了 v1 /api/v1/memo 的接口
> 
> [usememos/memos#3394](https://github.com/usememos/memos/issues/3394)

同样遇到了这样的问题，所以现在还能memos同步到obsidian，如果可以的话需要怎么修改api链接呢，这是个对我来说挺重要的功能。

**Comment by quanru** [comment]
> > 0.22.0 的 memos 删了 v1 /api/v1/memo 的接口
> > [usememos/memos#3394](https://github.com/usememos/memos/issues/3394)
> 
> 同样遇到了这样的问题，所以现在还能memos同步到obsidian，如果可以的话需要怎么修改api链接呢，这是个对我来说挺重要的功能。

先降级吧，这个 breaking 方式：

1. 把原有的 v1/xxx 接口直接下掉
2. 把原有的 v2/yyy 接口改成 v1/yyy

原来用 v1 的 和 v2 的，都沉默了

**Comment by quanru** [comment]
有人有兴趣帮忙提个 merge request 兼容一下吗？

**Comment by quanru** [comment]
新旧对应：
|              | 旧                                               | 新                                                                   |     |
| ------------ | ----------------------------------------------- | ------------------------------------------------------------------- | --- |
| Memos 列表     | /api/v1/memo?limit=50&offset=0&rowStatus=NORMAL | /api/v1/memos?page=1&pageSize=2&filter=created_ts_after==1697792882 |     |
| Resources 列表 | /api/v1/resource                                | /api/v1/resources                                                   |     |
| Resource 下载  | /o/r/:id                                        | /api/v1/resources/:id                                               |     |
