### ISSUE TITLE
领域中列出的任务来自于dailynote，如果完成可否隐藏

### ISSUE THREAD

**Issue by chinyajie** [quanru/obsidian-lifeos#71]
hi，您好。
领域中列出的任务来自于dailynote内容打tag，请问如果是todo完成，可否从领域的任务下隐藏。
lifeos插件包了dataview，实现了更为方便的TaskListByTag这样的语法，请问能否在上面扩展filter功能呢？
谢谢

**Comment by quanru** [comment]
已完成的任务已经排在最下面了，目前暂无扩展 filter 功能的计划
