### ISSUE TITLE
*.README文件无法按照tag索引到所有文件

### ISSUE THREAD

**Issue by huddao** [quanru/obsidian-lifeos#73]
如题，*.README无法索引到使用templater模板新增的文档，只有手动新增的文档添加了属性之后才能被索引到。

但是通过dataview直接索引对应的tag又可以列出所有的文档，所以不太清楚LifeOS内部是怎样实现的。

希望您能帮忙解答，感谢！

templater模板如下：
![image](https://github.com/quanru/obsidian-lifeos/assets/31430997/c4033443-e7da-42bc-92f7-8d8b783e1a0d)

**Comment by huddao** [comment]
.README文件可以索引到的文件：新建文档中的文档信息为空，再手动添加tags信息的文档。

但是通过dataview直接索引对应的tag又可以列出所有的文档，所以不太清楚LifeOS内部是怎样实现的。

希望您能帮忙解答，感谢！

**Comment by quanru** [comment]
是指『模式』没法被索引吗？

**Comment by quanru** [comment]
> 已经打上了对应的tag，但是索引不到

README 文件和被索引文件的内容发上来

**Comment by huddao** [comment]
[LifeOS排错示例.zip](https://github.com/user-attachments/files/16162804/LifeOS.zip)

**Comment by quanru** [comment]
@huddao 已修复，升级到 1.16.3

**Comment by huddao** [comment]
> @huddao 已修复，升级到 1.16.3

您好，已经升级到1.16.3的LifeOS，但还是不能索引到，我的obsidian版本是1.6.5，请问和这个有关系吗

**Comment by huddao** [comment]
经过排查，只要使用quickadd用templater模板添加的笔记就不能被索引

**Comment by quanru** [comment]
你给我的示例，我能复现，原因是文件名是日期开头的，我上次说修复，就是修复这个bug，而且你的示例在新版本里表现正常了，你确定更新了？更新后重启 Obsidian 试试

**Comment by huddao** [comment]
确定是不可以的。obsidian版本是1.6.5，直接建了新库，仅安装最版本的LifeOS、dataview、tasks和templater依然只能识别到手动创建的，安装插件后已经重启过obsidian
![image](https://github.com/user-attachments/assets/97810908-60cb-4590-b059-f5eade447d89)
![image](https://github.com/user-attachments/assets/0c09775a-0465-4234-8763-ea81e93fa79c)

**Comment by quanru** [comment]
好家伙，代码忘记带上了，稍后更新下：1.17.1

**Comment by huddao** [comment]
太好了，更新完后已经可以正常显示所有带对应tag的文件。
也会显示周日笔记文件，这里如果可以给个是否显示周期笔记的开关就更好了，能自己配置路径的那种。
![image](https://github.com/user-attachments/assets/f6477894-75ba-48d3-a216-45442efbc273)

**Comment by quanru** [comment]
> 太好了，更新完后已经可以正常显示所有带对应tag的文件。 也会显示周日笔记文件，这里如果可以给个是否显示周期笔记的开关就更好了，能自己配置路径的那种。 ![image](https://private-user-images.githubusercontent.com/31430997/349949418-f6477894-75ba-48d3-a216-45442efbc273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTUxMDEsIm5iZiI6MTcyMTM1NDgwMSwicGF0aCI6Ii8zMTQzMDk5Ny8zNDk5NDk0MTgtZjY0Nzc4OTQtNzViYS00OGQzLWEyMTYtNDU0NDJlZmJjMjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAyMDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ODA5NTNjZDJhMDUwYjhhMjA3MjhkOGZiNmNjZWJiYjdjM2VjNTBiNDk3Y2ZiMWY1ZjYzMGI2NDZlN2Q5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aOumy3sxcigCq8TaFPU0fkWrbiZvmkw_tWCbXK6JXIA)

你提一个 Issue 记录下
