### ISSUE TITLE
Periodic-para plugin fails to fetch usememos data, misinterpreting valid JSON response as an error

### ISSUE THREAD

**Issue by zubayrrr** [quanru/obsidian-lifeos#74]
The periodic-para plugin is encountering an error when attempting to fetch data from the usememos service. The plugin is incorrectly interpreting a valid JSON response as an error, leading to an uncaught promise rejection.

## Error Message

```
plugin:periodic-para:36514 Uncaught (in promise) Error: Fetch usememos failed: Error: {"memos":[...]}
    at logMessage (plugin:periodic-para:36514:11)
    at DailyRecord.fetch (plugin:periodic-para:39382:7)
    at async DailyRecord.insertDailyRecord (plugin:periodic-para:39228:23)
```

## Details

- The error occurs in the `fetch` method of the `DailyRecord` class.
- The JSON response contains an array of memo objects, each with properties such as name, uid, content, visibility, etc.
- Despite receiving what appears to be valid data, the plugin is treating this as an error response.

## Expected Behavior

The plugin should successfully parse the JSON response and process the memo data without throwing an error.

## Environment

- Plugin: periodic-para
- Plugin version: 1.15.2
- Obsidian version: v1.6.5
- Operating System: Kubuntu 23.10 x86_64

**Comment by zubayrrr** [comment]
I reinstalled the plugin and its now throwing the following error:

plugin:periodic-para:38598 
 GET https://my-memo.com/api/v1/resource 404 (Not Found)
plugin:periodic-para:38598 
 GET https://my-memo.com/api/v1/memo?limit=50&offset=0&rowStatus=NORMAL 404 (Not Found)
plugin:periodic-para:36513 Fetch usememos failed: AxiosError: Request failed with status code 404
plugin:periodic-para:36514 Uncaught (in promise) Error: Fetch usememos failed: AxiosError: Request failed with status code 404
    at logMessage (plugin:periodic-para:36514:11)
    at DailyRecord.fetch (plugin:periodic-para:39382:7)
    at async DailyRecord.insertDailyRecord (plugin:periodic-para:39228:23)

**Comment by quanru** [comment]
#68
