### ISSUE TITLE
LifeOS queries treat tags as case sensitive

### ISSUE THREAD

**Issue by technotherion** [quanru/obsidian-lifeos#78]
In Obsidian, tags are case insensitive. But if you create a project with the tag #project1 but then tag your tasks with #Project1, it will not show on the #project1 page. Regex, maybe? 

My workaround has been to use Tag Wrangler to rename and manage the uppercase or lowercase nature of each tag and make them all lowercase.

**Comment by quanru** [comment]
dataview query method does not support:
https://github.com/quanru/obsidian-periodic-para/blob/main/src/periodic/Task.ts#L145
