### ISSUE TITLE
Archived folders not found if any folder under Archive is missing a readme

### ISSUE THREAD

**Issue by technotherion** [quanru/obsidian-lifeos#79]
In the LifeOS testing vault I have created a folder called "testing"in "4. Archives" with the tag #work. Under the "Work" area, "testing" shows up under archive. 

![image](https://github.com/user-attachments/assets/a80c5ebc-3dc7-4191-8932-04945b8f5a16)
![image](https://github.com/user-attachments/assets/4da9094d-299d-4b64-9edb-73c9ca7aa200)

I then create another folder within "4. Archives" called "Not A Test". There's nothing inside of this folder, not even a readme.
I go back to the "Work" area and the Archived section is now empty. 

![image](https://github.com/user-attachments/assets/3ca6f2cd-f2ea-4bc2-8f90-91f7a631ce52)

I create "Not A Test.readme" and go back to the "Work" area. "Testing" has reappeared under Archive. 

I then go to "Not A Test.readme" and give it the tag #work. Both archived folders now show under the Archived section.
![image](https://github.com/user-attachments/assets/798a0f13-49dd-4cac-ad47-e5cb7915c886)

I then go back to "Not A Test" and remove the tag #work. "testing" still shows under the Work area. 

Creating any new folder without a Readme again repeats the process of no folders showing up under Archive.

**Comment by quanru** [comment]
Having an index file is a convention of a PARA note
