### ISSUE TITLE
ArchiveListByTag does not search within subdirectories of Archive

### ISSUE THREAD

**Issue by technotherion** [quanru/obsidian-lifeos#80]
## The Issue

Following the example provided in my previous issue, "testing" and "Not A Test" are both directories within the "4. Archives" folder with the tag #work in their readme files. 
![image](https://github.com/user-attachments/assets/fd788bf7-82e3-4e3f-a047-27eda7ae5b5b)
Now I will make "Not A Test" a subdirectory of "testing" and you will see that "Not A Test" no longer appears on the "Work" area page. 
![image](https://github.com/user-attachments/assets/315d0896-0088-4b27-8154-05cddf5e2fed)

In these examples, the underlined folders have the readme files set as Folder Notes. This is also what I do in my main repo.

## My use case 

This is an issue in my main vault because I retain the directory structure of my projects, areas and resources under "4. Archive". Here's an example:
![image](https://github.com/user-attachments/assets/715a8de4-236b-4a99-8c92-898067f45903)

Here's a bunch of archived projects. They all have the #career/comm tag in their readmes. 
![image](https://github.com/user-attachments/assets/10f46e66-2593-43f6-91da-6b07eff6070b)

None of these projects show under the "Career" Area. 
![image](https://github.com/user-attachments/assets/48631b6f-561b-4160-9f3a-910346c72b35)

However, if I drag one of these projects outside of the project folder into "4. Archive"...
![image](https://github.com/user-attachments/assets/cc54cbbd-29d0-400e-9bc2-8d686136d0af)

Then it shows up correctly under the Career Area page. 
![image](https://github.com/user-attachments/assets/395bc1d4-a725-4aef-8d9c-c18e03124f11)

## Considerations
I know that searching down subdirectories can be costly to system resources, especially if an archive is especially large. Would it  be possible to whitelist some subdirectories for LifeOS to be able to search down by one directory? That way, it's not checking every single readme file in the archive.

**Comment by quanru** [comment]
The practice in PARA is to pat the folder flat. This is not recommended
