### ISSUE TITLE
Custom template locations not working

### ISSUE THREAD

**Issue by TheRealPJC** [quanru/obsidian-lifeos#81]
The new settings for custom template locations for PARA notes do not work. 

In the advanced settings window, I set a custom Project template to the path "Assets/templates/Project_template.md". This file exists. 

However, when I go to create a new project with the note creation module, I get the error: 

> There is no template file exists.1. 
> Templates/Project.md

Occurs on Obsidian v1.6.7 on PopOS.

**Comment by quanru** [comment]
what's your lifeos plugin version

**Comment by TheRealPJC** [comment]
Sorry, should have said: LifeOS v1.17.4

**Comment by quanru** [comment]
It should be your wrong configuration. Send .obsidian/plugins/periodic-para/data.json
