### ISSUE TITLE
周期笔记是否能够支持类似periodic-notes的自定义格式

### ISSUE THREAD

**Issue by htyeim** [quanru/obsidian-lifeos#83]
感谢这个插件的开发！相关的功能对整体的笔记使用有非常大的提升和帮助。

有一个关于周期笔记的建议，因为本身使用的periodic-notes（https://github.com/liamcain/obsidian-periodic-notes
）插件，并自定义了文件格式，同时已经有较多笔记文件了。想使用这个功能，但无法兼容原有文件，比较难处理。
不知道是否可以提供类似的自定义功能？

<img width="756" alt="image" src="https://github.com/user-attachments/assets/940d4219-16a6-4ded-b44d-ee217c995804">

**Comment by quanru** [comment]
Duplicate #85
