### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by lorenzo-lepore** [quanru/obsidian-lifeos#84]
**Problem:** can't enable the plugin. An error is shown, saying _Failed to load plugin: "periodic-para"_.

**How to reproduce:** install the plugin and click on the enable button in the plugin page.

I've tried disabling all my other third part plugins. Wasn't of any help.

`Obsidian version: 1.6.7`

![image](https://github.com/user-attachments/assets/777730a6-8183-4f75-b512-ee808f022ff1)

**Comment by quanru** [comment]
open console to see if there are any errors about the lifeos plugin:

mac: cmd+alt+i
windows: ctrl+shift+i

**Comment by lorenzo-lepore** [comment]
It seems that the Dataview plugin was needed. Installed it and now everything works fine! Thank you ;)

![image](https://github.com/user-attachments/assets/aba14393-cd88-40a6-a066-239d90de163a)

**Comment by quanru** [comment]
This is indeed a bug, the normal should pop-up window prompt, I will fix
