### ISSUE TITLE
md文件名开头只要超过3个数字，FileListByTag列表就不会显示这个文件

### ISSUE THREAD

**Issue by yanghuatjy** [quanru/obsidian-lifeos#86]
![Quicker_20240913_125746](https://github.com/user-attachments/assets/a823d5a3-091a-4b9f-95f7-590c944613de)
![Quicker_20240913_125806](https://github.com/user-attachments/assets/ca2522d1-cc60-4f89-88a6-82959dd4fa2c)

这是bug吗？

**Comment by quanru** [comment]
插件版本多少？

**Comment by yanghuatjy** [comment]
> 插件版本多少？

一直最新版本，现在lifeos是1.17.7

**Comment by quanru** [comment]
@yanghuatjy 已修复，谢谢反馈，麻烦更新到 1.17.8
