### ISSUE TITLE
Project.snapshot() incompatible with Callouts

### ISSUE THREAD

**Issue by wedgen** [quanru/obsidian-lifeos#90]
I'm collecting my projects in a callout for my Daily notes however the snapshot function will place the first project into the callout but the rest do not.  I'm curious how to get templater to place a `>` for each new link. 

my markdown is as followed. 
```
>[!question]- Projects
><% LifeOS.Project.snapshot() %>
```

**Comment by quanru** [comment]
This syntax belongs to Templater and is unrelated to the LifeOS plugin.

**Comment by wedgen** [comment]
You provided that function to be used with templater, it would be nice if it worked well with the echosystem of Obsidian and their callouts.
