### ISSUE TITLE
对于字体的适配

### ISSUE THREAD

**Issue by LightYear512** [quanru/obsidian-lifeos#91]
插件中部分文字似乎没有使用Obsidian中配置的字体, 字体对比见下图
![image](https://github.com/user-attachments/assets/f167528b-4b82-4bbb-8eb3-e13d0763543f)
![image](https://github.com/user-attachments/assets/c737811b-7173-4f00-aadb-6c22ba503848)
Obsidian外观配置见下图
![image](https://github.com/user-attachments/assets/f3d1f0d6-82c3-4341-af2c-553f9415f6f6)

**Comment by LightYear512** [comment]
非常感谢您在1.20.0版本对字体的修复，会继续支持您的。

**Comment by quanru** [comment]
@LightYear512 谢谢支持哈~
